import type * as Bitstream from './Bitstream.js'

export const functionBlock: Bitstream.Block = Object.freeze({ id: 12, abbreviations: [] })

export const code = Object.freeze({
  declareBlocks: 1,
  binary: 2,
  cast: 3,
  extractElement: 6,
  insertElement: 7,
  shuffleVector: 8,
  return: 10,
  branch: 11,
  switch: 12,
  unreachable: 15,
  phi: 16,
  alloca: 19,
  load: 20,
  vaArg: 23,
  extractValue: 26,
  insertValue: 27,
  compare: 28,
  select: 29,
  indirectBranch: 31,
  call: 34,
  fence: 36,
  atomicRmw: 38,
  loadAtomic: 41,
  getElementPtr: 43,
  store: 44,
  storeAtomic: 45,
  compareExchange: 46,
  unary: 56,
  freeze: 58,
})

export const binaryOpcode = Object.freeze({
  add: 0,
  fadd: 0,
  sub: 1,
  fsub: 1,
  mul: 2,
  fmul: 2,
  udiv: 3,
  fdiv: 4,
  sdiv: 4,
  urem: 5,
  frem: 6,
  srem: 6,
  shl: 7,
  lshr: 8,
  ashr: 9,
  and: 10,
  or: 11,
  xor: 12,
})

export const castOpcode = Object.freeze({
  trunc: 0,
  zext: 1,
  sext: 2,
  fptoui: 3,
  fptosi: 4,
  uitofp: 5,
  sitofp: 6,
  fptrunc: 7,
  fpext: 8,
  ptrtoint: 9,
  inttoptr: 10,
  bitcast: 11,
  addrspacecast: 12,
})

export const integerPredicate = Object.freeze({
  eq: 32,
  ne: 33,
  ugt: 34,
  uge: 35,
  ult: 36,
  ule: 37,
  sgt: 38,
  sge: 39,
  slt: 40,
  sle: 41,
})

export const floatingPredicate = Object.freeze({
  false: 0,
  oeq: 1,
  ogt: 2,
  oge: 3,
  olt: 4,
  ole: 5,
  one: 6,
  ord: 7,
  uno: 8,
  ueq: 9,
  ugt: 10,
  uge: 11,
  ult: 12,
  ule: 13,
  une: 14,
  true: 15,
})
