import type * as AuthoredHir from '../../src/AuthoredHir.js'
import type * as SyntaxTree from '../../src/SyntaxTree.js'

type Disposition =
  | AuthoredHir.Record['_tag']
  | readonly AuthoredHir.Record['_tag'][]
  | { readonly container: string }
  | { readonly recovery: readonly AuthoredHir.Record['_tag'][]; readonly reason: string }

/**
 * Compile-time grammar inventory for the authored boundary. Containers contribute ordered
 * fields to their parent; this table does not execute the future syntax-lowering pass.
 * Adding a grammar kind or removing its authored representation requires a deliberate update.
 */
export const authoredSyntaxCoverage = {
  SourceFile: { container: 'AuthoredModule.declarations and its module-owned pool' },
  ImportDeclaration: 'ImportHeader',
  StaticConditionalDeclaration: 'ConditionalHeader',
  DeclarationGroup: 'GroupHeader',
  ImportPath: 'Path',
  ImportAlias: 'Name',
  ImportMemberList: { container: 'ImportHeader.members in authored order' },
  ImportMember: 'ImportMember',
  StructDeclaration: 'StructHeader',
  TupleDeclaration: 'TupleHeader',
  EnumDeclaration: 'EnumHeader',
  EnumMember: 'EnumMember',
  UnionDeclaration: 'UnionHeader',
  UnionVariant: 'Variant',
  UnionVariantField: 'Field',
  AppliedMemberSelector: 'MemberSelector',
  AppliedMemberExpression: 'MemberExpression',
  UnionVariantPattern: 'VariantPattern',
  ServiceDeclaration: 'ServiceHeader',
  InterfaceDeclaration: 'InterfaceHeader',
  RoleDeclaration: 'RoleHeader',
  RequirementSelector: 'RequirementSelector',
  ServiceOperation: 'OperationHeader',
  OperatorMarker: { container: 'OperationHeader.operator preserves the operation marker' },
  ServiceInvalidMember: {
    recovery: ['InvalidDeclarationHeader', 'InvalidDeclarationBody'],
    reason: 'Retain the local recovery cause and healthy member structure',
  },
  ConstantDeclaration: 'ConstantHeader',
  PackageParameterDeclaration: 'PackageParameterHeader',
  PackageParameterValidation: { container: 'PackageParameterBody.validation expression' },
  TypeAliasDeclaration: 'AliasHeader',
  StructField: 'Field',
  ImplDeclaration: 'ImplHeader',
  ImplOperation: 'ImplAliasHeader',
  TypeParameterList: { container: 'Ordered generic parameters on the owning header or contract' },
  TypeParameter: ['TypeParameter', 'RowParameter'],
  LifetimeParameter: 'LifetimeParameter',
  LifetimeType: 'Lifetime',
  LifetimeBinderList: { container: 'Ordered LifetimeParameter binders' },
  EffectEnvironment: {
    container: 'CallableContract.environment preserves explicit empty presence',
  },
  CallableEnvironment: { container: 'CallableType.environment lifetime' },
  TypePath: 'NamedType',
  AppliedType: 'AppliedType',
  TypeArgumentList: 'TypeArguments',
  FixedArrayType: 'FixedArrayType',
  SliceType: 'SliceType',
  ReferenceType: 'ReferenceType',
  PointerType: 'PointerType',
  PointerQualifier: 'PointerQualifier',
  CallableType: 'CallableType',
  ForeignFunctionType: 'ForeignFunctionType',
  ExactRepresentationType: 'ExactRepresentationType',
  OpaqueResultType: 'OpaqueResultType',
  UnitType: 'UnitType',
  ParenthesizedType: {
    container: 'The enclosed type; grouping has no independent authored meaning',
  },
  UnionType: 'UnionType',
  FunctionDeclaration: 'FunctionHeader',
  ForeignFunctionDeclaration: 'FunctionHeader',
  ModulePropertyDeclaration: 'ModulePropertyHeader',
  FunctionPropertyClause: 'PropertyClause',
  FunctionProperty: 'Property',
  ForeignStaticDeclaration: 'StaticHeader',
  ExportStaticDeclaration: 'StaticHeader',
  FailureRow: { container: 'CallableContract.failures or TypeArguments.failures type' },
  RequirementRow: 'RequirementRow',
  Requirement: 'Requirement',
  RowWithout: 'RowWithout',
  WhereClause: { container: 'CallableContract.constraints in authored order' },
  MembershipConstraint: 'MembershipConstraint',
  ProviderConstraint: 'ProviderConstraint',
  ParameterList: { container: 'CallableContract.parameters in authored order and variadic marker' },
  ParameterDeclaration: 'Parameter',
  ReturnType: { container: 'CallableContract.result type' },
  Block: 'Block',
  ExpressionStatement: 'ExpressionStatement',
  ErrorStatement: {
    recovery: ['MissingStatement', 'InvalidStatement'],
    reason: 'Keep statement-local causes and any healthy retained expressions or statements',
  },
  BindingStatement: 'BindingStatement',
  PatternBindingStatement: 'PatternBindingStatement',
  AssignmentStatement: 'AssignmentStatement',
  ConditionalStatement: 'ConditionalStatement',
  StaticConditionalStatement: 'StaticConditionalStatement',
  StaticForStatement: 'StaticForStatement',
  PatternConditionalStatement: 'PatternConditionalStatement',
  WhileStatement: 'WhileStatement',
  BreakStatement: 'BreakStatement',
  ContinueStatement: 'ContinueStatement',
  ReturnStatement: 'ReturnStatement',
  FailStatement: 'FailStatement',
  DropStatement: 'DropStatement',
  UnsafeStatement: 'UnsafeStatement',
  UnsafeExpression: 'UnsafeExpression',
  CompileErrorExpression: 'CompileErrorExpression',
  IntegerLiteralExpression: 'IntegerLiteral',
  DurationLiteralExpression: 'DurationLiteral',
  FloatingLiteralExpression: 'FloatingLiteral',
  StaticTextLiteralExpression: ['TextLiteral', 'BytesLiteral', 'InvalidExpression'],
  CharacterLiteralExpression: 'CharacterLiteral',
  UnitExpression: 'UnitLiteral',
  BooleanLiteralExpression: 'BooleanLiteral',
  IdentifierExpression: 'IdentifierExpression',
  MoveExpression: 'MoveExpression',
  AnonymousCallableExpression: 'CallableExpression',
  EffectExpression: 'EffectExpression',
  RunExpression: 'RunExpression',
  BorrowExpression: 'BorrowExpression',
  MatchExpression: 'MatchExpression',
  MatchAccess: {
    container: 'MatchExpression.access preserves default, place, move and borrow modes',
  },
  MatchArm: 'MatchArm',
  ErrorPattern: {
    recovery: ['MissingPattern', 'InvalidPattern'],
    reason: 'Keep pattern-local causes and healthy retained patterns',
  },
  EnumMemberPattern: 'EnumPattern',
  IntegerPattern: 'IntegerPattern',
  NominalPattern: 'NominalPattern',
  BindingPattern: 'BindingPattern',
  UniversalPattern: 'UniversalPattern',
  PatternField: 'PatternField',
  RestPattern: 'RestPattern',
  StructLiteralExpression: 'StructExpression',
  TupleLiteralExpression: 'TupleExpression',
  ContextualRecordLiteralExpression: 'RecordExpression',
  ArrayLiteralExpression: 'ArrayExpression',
  StructFieldInitializer: 'FieldInitializer',
  FieldProjectionExpression: 'FieldExpression',
  OrdinalProjectionExpression: 'OrdinalExpression',
  ReferentProjectionExpression: 'ReferentExpression',
  IndexProjectionExpression: 'IndexExpression',
  CallExpression: 'CallExpression',
  CallTypeArgumentList: 'TypeArguments',
  GroupedExpression: {
    container: 'The enclosed expression; grouping is already reflected in operand structure',
  },
  PrefixExpression: 'PrefixExpression',
  InfixExpression: 'InfixExpression',
  PipelineExpression: 'PipelineExpression',
  ArgumentList: { container: 'CallExpression.arguments in evaluation order' },
  Error: {
    recovery: [
      'MissingExpression',
      'InvalidExpression',
      'MissingType',
      'InvalidType',
      'MissingName',
    ],
    reason: 'The containing semantic position chooses its recovery record and retains local causes',
  },
} as const satisfies Record<SyntaxTree.NodeKind, Disposition>
