/** Ordered native-corpus programs promised by the self-hosted compiler. */
export const selfhostTrack = [
  'literal',
  'foreign-libc-abs',
  'foreign-libc-pointer-roundtrip',
  'foreign-libc-floating',
  'sealed-scalar-intrinsics',
  'scalar-reference-read',
  'scalar-reference-write-through',
  'scalar-reference-argument-order',
  'mutable-struct-loop',
  'recursive-aggregate-return',
  'inherent-member-over-module-projection',
  'generic-specializations',
  'generic-partial-type-arguments',
  'same-specialization-recursion',
  'array-inferred',
  'array-contextual-empty',
  'array-nested',
  'array-indexed-struct-field',
  'array-whole-move',
  'array-upper-index-trap',
  'array-zero-index-trap',
  'mutable-array-loop',
  'usize-array-roundtrip',
  'algorithm-sieve',
  'runtime-indexed-subplace-borrow',
  'short-circuit-counting',
] as const satisfies ReadonlyArray<string>
