import type * as Token from '../Token.js'

export const expressionFollowing: ReadonlyArray<Token.TokenKind> = Object.freeze([
  'Comma',
  'RightParenthesis',
  'RightBracket',
  'LeftBrace',
  'RightBrace',
  'Equals',
  'FatArrow',
  'LetKeyword',
  'ConstKeyword',
  'IfKeyword',
  'WhileKeyword',
  'BreakKeyword',
  'ContinueKeyword',
  'ReturnKeyword',
  'FailKeyword',
  'DropKeyword',
  'UnsafeKeyword',
  'ElseKeyword',
  'PubKeyword',
  'StructKeyword',
  'FnKeyword',
  'EffectKeyword',
  'ImportKeyword',
  'ImplKeyword',
  'MatchKeyword',
])

export const expressionStarts: ReadonlyArray<Token.TokenKind> = Object.freeze([
  'DecimalInteger',
  'DecimalFloat',
  'TextLiteral',
  'ByteStringLiteral',
  'CharLiteral',
  'InvalidStaticLiteral',
  'Identifier',
  'LeftBrace',
  'MoveKeyword',
  'TrueKeyword',
  'FalseKeyword',
  'Minus',
  'Bang',
  'Tilde',
  'LeftParenthesis',
  'LeftBracket',
  'MatchKeyword',
  'EffectKeyword',
  'RunKeyword',
  'Less',
  'Ampersand',
  'UnsafeKeyword',
])

export const typeStarts: ReadonlyArray<Token.TokenKind> = Object.freeze([
  'Identifier',
  'UnsafeKeyword',
  'FnKeyword',
  'MutKeyword',
  'OnceKeyword',
  'LeftParenthesis',
  'LeftBracket',
  'Ampersand',
])
export const topLevelFollowing: ReadonlyArray<Token.TokenKind> = Object.freeze([
  'ImportKeyword',
  'PubKeyword',
  'ConstKeyword',
  'StructKeyword',
  'ServiceKeyword',
  'InterfaceKeyword',
  'RoleKeyword',
  'FnKeyword',
  'EffectKeyword',
  'UnsafeKeyword',
  'ImplKeyword',
  'EndOfFile',
])
