import * as Context from 'effect/Context'
import * as Data from 'effect/Data'
import * as Effect from 'effect/Effect'
import * as Layer from 'effect/Layer'
import * as Option from 'effect/Option'
import * as SourceOrigin from './SourceOrigin.js'
import * as Stdlib from './Stdlib.js'

/** Exact resolved bytes together with the source location that supplied them. */
export interface ResolvedSource {
  readonly bytes: Uint8Array
  readonly origin: SourceOrigin.SourceOrigin
}

/** Copies resolved bytes into one immutable resolution fact. */
export const resolved = (bytes: Uint8Array, origin: SourceOrigin.SourceOrigin): ResolvedSource =>
  Object.freeze({ bytes: Uint8Array.from(bytes), origin })

/** Why a source resolver could not determine the bytes for one canonical module identity. */
export type SourceResolverErrorReason =
  | { readonly _tag: 'InvalidModuleIdentity' }
  | { readonly _tag: 'MissingToolchainSource'; readonly path: string }
  | { readonly _tag: 'WrappedFailure'; readonly cause: unknown }

/** A typed operational failure at the source-storage boundary. */
export class SourceResolverError extends Data.TaggedError('SourceResolverError')<{
  readonly operation: string
  readonly module: string
  readonly message: string
  readonly reason: SourceResolverErrorReason
  readonly cause?: unknown
}> {
  constructor(options: {
    readonly operation: string
    readonly module: string
    readonly message: string
    readonly reason: SourceResolverErrorReason
  }) {
    super(
      options.reason._tag === 'WrappedFailure'
        ? { ...options, cause: options.reason.cause }
        : options,
    )
  }
}

/** Tests whether a string is a canonical, extensionless Silk module identity. */
export const isCanonicalModule = (module: string): boolean =>
  module.length > 0 &&
  !module.startsWith('/') &&
  !module.endsWith('/') &&
  !module.includes('\\') &&
  module
    .split('/')
    .every(
      (segment) =>
        segment.length > 0 &&
        segment !== '.' &&
        segment !== '..' &&
        /^[A-Za-z0-9_-]+$/.test(segment),
    )

/** The replaceable capability used to resolve imported source bytes. */
export class SourceResolver extends Context.Service<
  SourceResolver,
  {
    readonly resolve: (
      module: string,
    ) => Effect.Effect<Option.Option<ResolvedSource>, SourceResolverError>
    readonly resolveStandardLibrary: (
      module: string,
    ) => Effect.Effect<Option.Option<ResolvedSource>, SourceResolverError>
  }
>()('@silk-effect/compiler/SourceResolver') {}

/** Resolves one validated canonical module through the active source resolver. */
export const resolve = Effect.fn('SourceResolver.resolve')(function* (
  module: string,
): Effect.fn.Return<Option.Option<ResolvedSource>, SourceResolverError, SourceResolver> {
  if (!isCanonicalModule(module)) {
    return yield* new SourceResolverError({
      operation: 'SourceResolver.resolve',
      module,
      message: `Source module identity ${module} is not canonical`,
      reason: { _tag: 'InvalidModuleIdentity' },
    })
  }
  const resolver = yield* SourceResolver
  return Option.map(yield* resolver.resolve(module), (source) =>
    resolved(source.bytes, source.origin),
  )
})

/** Resolves one reserved module through the active toolchain source policy. */
export const resolveStandardLibrary = Effect.fn('SourceResolver.resolveStandardLibrary')(function* (
  module: string,
): Effect.fn.Return<Option.Option<ResolvedSource>, SourceResolverError, SourceResolver> {
  if (!Stdlib.isReserved(module) || !isCanonicalModule(module)) {
    return yield* new SourceResolverError({
      operation: 'SourceResolver.resolveStandardLibrary',
      module,
      message: `Standard-library module identity ${module} is not canonical and reserved`,
      reason: { _tag: 'InvalidModuleIdentity' },
    })
  }
  const resolver = yield* SourceResolver
  return Option.map(yield* resolver.resolveStandardLibrary(module), (source) =>
    resolved(source.bytes, source.origin),
  )
})

/** Resolves shipped generated bytes for host-filesystem-free tooling. */
export const resolveEmbeddedStandardLibrary = Effect.fn(
  'SourceResolver.resolveEmbeddedStandardLibrary',
)((module: string): Effect.Effect<Option.Option<ResolvedSource>> => {
  const bytes = Stdlib.sources.get(module)
  return Effect.succeed(
    bytes === undefined ? Option.none() : Option.some(resolved(bytes, SourceOrigin.memory())),
  )
})

/** An immutable in-memory resolver layer suitable for browsers, tooling, and tests. */
export const memory = (sources: ReadonlyMap<string, Uint8Array>): Layer.Layer<SourceResolver> => {
  const snapshot = new Map(
    [...sources].map(([module, bytes]) => [module, Uint8Array.from(bytes)] as const),
  )
  return Layer.succeed(SourceResolver, {
    resolve: Effect.fn('SourceResolver.memory.resolve')((module: string) => {
      const bytes = snapshot.get(module)
      return Effect.succeed(
        bytes === undefined ? Option.none() : Option.some(resolved(bytes, SourceOrigin.memory())),
      )
    }),
    resolveStandardLibrary: resolveEmbeddedStandardLibrary,
  })
}

/** A resolver layer that authoritatively reports every imported module as absent. */
export const empty: Layer.Layer<SourceResolver> = memory(new Map())
