// Generated by scripts/generate-toolchain-integrity.mjs. Do not edit.

<<<<<<< HEAD
export const compilerDigest = 'e37c150393f99df1a3af773d1d9f1555a26a81ab447e0a9188e5452dc51a75a9'
=======
export const compilerDigest = '7b720cc82d6141678336ae7b6972d3046ea634188f3287b3c8b335a2c6570c6f'
>>>>>>> f42d8f0 (fix(formatter): keep effect clauses inline when they fit the line)
