import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const stdlibRoot = join(packageRoot, 'stdlib')
const manifestPath = join(stdlibRoot, 'manifest.json')
const outputPath = join(packageRoot, 'src', 'Stdlib.generated.ts')

const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
const canonicalModule = /^[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*$/
const layers = new Set(['portable', 'target-provider'])
const executionTargets = [
  'aarch64-apple-darwin',
  'aarch64-unknown-linux-gnu',
  'wasm32-unknown-unknown',
  'x86_64-unknown-linux-gnu',
]
const staticIntrinsics = new Set([
  'targetArchitecture',
  'targetOperatingSystem',
  'targetAbi',
  'targetObjectFormat',
  'targetEndianness',
  'targetPointerBits',
  'targetPointerAlignment',
  'profileText',
  'profileFlag',
  'profileContains',
])
const modules = []

const sourceLiteral = (source) => {
  const singleQuotes = [...source].filter((character) => character === "'").length
  const doubleQuotes = [...source].filter((character) => character === '"').length
  if (singleQuotes > doubleQuotes) return JSON.stringify(source)
  return `'${JSON.stringify(source).slice(1, -1).replaceAll('\\"', '"').replaceAll("'", "\\'")}'`
}

const aliasesLiteral = (aliases) => {
  const quoted = aliases.map((alias) => `'${alias}'`)
  const inline = `[${quoted.join(', ')}]`
  if (inline.length <= 80) return inline
  return `[\n${quoted.map((alias) => `      ${alias},`).join('\n')}\n    ]`
}

for (const [index, entry] of manifest.entries()) {
  if (
    typeof entry?.module !== 'string' ||
    typeof entry?.path !== 'string' ||
    !layers.has(entry.layer) ||
    (entry.layer === 'portable' && entry.providerTargets !== undefined) ||
    (entry.layer === 'target-provider' &&
      (!Array.isArray(entry.providerTargets) ||
        entry.providerTargets.length === 0 ||
        entry.providerTargets.some((target) => !executionTargets.includes(target)) ||
        executionTargets.filter((target) => entry.providerTargets.includes(target)).join() !==
          entry.providerTargets.join())) ||
    (entry.namespace !== undefined && typeof entry.namespace !== 'string') ||
    (entry.namespace !== undefined && !/^[A-Za-z_][A-Za-z0-9_]*$/.test(entry.namespace)) ||
    (entry.aliases !== undefined &&
      (!Array.isArray(entry.aliases) ||
        entry.aliases.some(
          (alias) => typeof alias !== 'string' || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(alias),
        ))) ||
    !canonicalModule.test(entry.module) ||
    entry.path !== `${entry.module}.silk`
  ) {
    throw new Error(`Invalid standard-library manifest entry at index ${index}`)
  }
  if (index > 0 && manifest[index - 1].module >= entry.module) {
    throw new Error('Standard-library manifest must be strictly ordered by canonical module')
  }
  const source = await readFile(join(stdlibRoot, entry.path), 'utf8')
  const imports = [...source.matchAll(/\bimport\s+([A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)*)/g)].map(
    (match) => match[1].replaceAll('.', '/'),
  )
  const intrinsicInventory = [
    ...new Set(
      [...source.matchAll(/\bIntrinsic\.([A-Za-z_][A-Za-z0-9_]*)/g)].map((match) => match[1]),
    ),
  ].sort()
  const staticInventory = intrinsicInventory.filter((operation) => staticIntrinsics.has(operation))
  const runtimeInventory = intrinsicInventory.filter(
    (operation) => !staticIntrinsics.has(operation),
  )
  modules.push({
    ...entry,
    sourceIdentity: entry.module,
    digest: createHash('sha256').update(source).digest('hex'),
    documentation: entry.path,
    imports,
    staticInventory,
    runtimeInventory,
    source,
  })
}

const byModule = new Map(modules.map((entry) => [entry.module, entry]))
for (const entry of modules) {
  for (const imported of entry.imports) {
    const dependency = byModule.get(imported)
    if (entry.layer === 'portable' && dependency?.layer === 'target-provider')
      throw new Error(
        `Portable standard-library module ${entry.module} imports target provider ${imported}`,
      )
  }
}

const entries = modules
  .map(
    (entry) => `  {
    module: '${entry.module}',
    path: '${entry.path}',
    sourceIdentity: '${entry.sourceIdentity}',
    digest: '${entry.digest}',
    documentation: '${entry.documentation}',
    layer: '${entry.layer}',
    ${entry.providerTargets === undefined ? '' : `providerTargets: ${aliasesLiteral(entry.providerTargets)},\n    `}staticInventory: ${aliasesLiteral(entry.staticInventory)},
    runtimeInventory: ${aliasesLiteral(entry.runtimeInventory)},
    ${entry.namespace === undefined ? '' : `namespace: '${entry.namespace}',\n    `}${entry.aliases === undefined ? '' : `aliases: ${aliasesLiteral(entry.aliases)},\n    `}source:
      ${sourceLiteral(entry.source)},
  },`,
  )
  .join('\n')
const generated = `// Generated by scripts/generate-stdlib.mjs. Do not edit.\n\nexport const modules = [\n${entries}\n] as const\n`
const check = process.argv.includes('--check')
const stdout = process.argv.includes('--stdout')

if (stdout) {
  process.stdout.write(generated)
} else if (check) {
  const current = await readFile(outputPath, 'utf8').catch(() => undefined)
  if (current !== generated) {
    throw new Error('Generated standard-library table is stale; run pnpm stdlib:generate')
  }
} else {
  await writeFile(outputPath, generated)
}
