import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const stdlibRoot = join(packageRoot, 'stdlib')
const manifestPath = join(stdlibRoot, 'manifest.json')
const outputPath = join(packageRoot, 'src', 'Stdlib.generated.ts')

const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
const canonicalModule = /^[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*$/
const modules = []

for (const [index, entry] of manifest.entries()) {
  if (
    typeof entry?.module !== 'string' ||
    typeof entry?.path !== 'string' ||
    !canonicalModule.test(entry.module) ||
    entry.path !== `${entry.module}.silk`
  ) {
    throw new Error(`Invalid standard-library manifest entry at index ${index}`)
  }
  if (index > 0 && manifest[index - 1].module >= entry.module) {
    throw new Error('Standard-library manifest must be strictly ordered by canonical module')
  }
  modules.push({ ...entry, source: await readFile(join(stdlibRoot, entry.path), 'utf8') })
}

const entries = modules
  .map(
    (entry) => `  {
    module: '${entry.module}',
    path: '${entry.path}',
    source:
      ${JSON.stringify(entry.source)},
  },`,
  )
  .join('\n')
const generated = `// Generated by scripts/generate-stdlib.mjs. Do not edit.\n\nexport const modules = [\n${entries}\n] as const\n`
const check = process.argv.includes('--check')

if (check) {
  const current = await readFile(outputPath, 'utf8').catch(() => undefined)
  if (current !== generated) {
    throw new Error('Generated standard-library table is stale; run pnpm stdlib:generate')
  }
} else {
  await writeFile(outputPath, generated)
}
