import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import * as Lexer from '@silk-effect/compiler/Lexer'
import * as SourceFile from '@silk-effect/compiler/SourceFile'
import { assert, it } from 'vitest'
import * as TextMate from '../src/TextMate.js'

const keywordScopeNames = new Set([
  'keyword.control.silk',
  'storage.type.silk',
  'constant.language.boolean.silk',
])

const lexKinds = (text: string): ReadonlyArray<string> =>
  Lexer.lex(SourceFile.make('test', new TextEncoder().encode(text)))
    .tokens.filter((token) => token.kind !== 'Whitespace' && token.kind !== 'EndOfFile')
    .map((token) => token.kind)

/** The keyword spellings the grammar actually matches, parsed back out of its regexes. */
const grammarKeywordSpellings = (): ReadonlyArray<string> =>
  TextMate.grammar.patterns
    .filter((pattern) => {
      if (pattern.name !== undefined && keywordScopeNames.has(pattern.name)) {
        return true
      }
      // `fn` is matched via captures on the function-declaration rule.
      return pattern.captures?.['1']?.name === 'storage.type.silk'
    })
    .flatMap((pattern) => {
      if (pattern.captures?.['1']?.name === 'storage.type.silk') {
        return ['fn']
      }
      const match = pattern.match
      assert.isDefined(match, `keyword pattern has no match expression: ${pattern.name}`)
      const alternation = match.match(/\(\?:([^)]*)\)/)
      assert.isNotNull(alternation, `keyword pattern has no alternation: ${match}`)
      return (alternation?.[1] ?? '').split('|')
    })

it('every declared keyword spelling lexes to its keyword token kind', () => {
  for (const [kind, spelling] of Object.entries(TextMate.keywords)) {
    assert.deepStrictEqual(lexKinds(spelling), [kind], `keyword ${spelling}`)
  }
})

it('the grammar matches exactly the compiler keyword set', () => {
  const fromGrammar = [...grammarKeywordSpellings()].sort()
  const fromCompiler = Object.values(TextMate.keywords).sort()
  assert.deepStrictEqual(fromGrammar, fromCompiler)
})

it('the VS Code extension ships exactly this grammar and configuration', () => {
  // The extension's files are generated by scripts/sync-vscode.mjs; regenerate when this fails.
  const extensionRoot = resolve(dirname(new URL(import.meta.url).pathname), '../../vscode')
  const readJson = (path: string): unknown => JSON.parse(readFileSync(path, 'utf8'))
  assert.deepStrictEqual(
    readJson(resolve(extensionRoot, 'syntaxes/silk.tmLanguage.json')),
    JSON.parse(JSON.stringify(TextMate.grammar)),
  )
  assert.deepStrictEqual(
    readJson(resolve(extensionRoot, 'language-configuration.json')),
    JSON.parse(JSON.stringify(TextMate.languageConfiguration)),
  )
})

it('assigns keyword, numeric, and comment scopes via a TextMate tokenizer', async () => {
  const { createHighlighter } = await import('shiki')
  const highlighter = await createHighlighter({
    themes: ['github-light'],
    langs: [TextMate.grammar as never],
  })
  const scopesAt = (line: string, text: string): ReadonlyArray<string> => {
    const tokens = highlighter.codeToTokensBase(line, {
      // The bundled-language type union does not know custom grammars.
      lang: 'silk' as never,
      theme: 'github-light',
      includeExplanation: true,
    })
    const token = tokens
      .flat()
      .find((candidate) => candidate.content.includes(text) && candidate.explanation !== undefined)
    assert.isDefined(token, `no token containing ${JSON.stringify(text)}`)
    return (token?.explanation ?? [])
      .filter((part) => part.content.includes(text))
      .flatMap((part) => part.scopes.map((scope) => scope.scopeName))
  }

  const program = 'pub fn main() -> i32 { return 42 }'
  assert.include(scopesAt(program, 'pub'), 'storage.type.silk')
  assert.include(scopesAt(program, 'fn'), 'storage.type.silk')
  assert.include(scopesAt(program, 'main'), 'entity.name.function.silk')
  assert.include(scopesAt(program, 'return'), 'keyword.control.silk')
  assert.include(scopesAt(program, 'i32'), 'support.type.builtin.silk')
  assert.include(scopesAt('impl Allocator for Mine { unsafe {} }', 'impl'), 'storage.type.silk')
  assert.include(scopesAt('impl Allocator for Mine { unsafe {} }', 'for'), 'storage.type.silk')
  assert.include(scopesAt('impl Allocator for Mine { unsafe {} }', 'unsafe'), 'storage.type.silk')
  assert.include(
    scopesAt('impl Allocator for Mine { unsafe {} }', 'Allocator'),
    'entity.name.type.silk',
  )
  assert.include(scopesAt(program, '42'), 'constant.numeric.integer.silk')
  assert.include(scopesAt('let ok = true', 'true'), 'constant.language.boolean.silk')
  assert.include(scopesAt('fn stop() -> never', 'never'), 'support.type.builtin.silk')
  assert.include(scopesAt('fn id(x: Point) -> Point', 'Point'), 'entity.name.type.silk')
  assert.include(scopesAt('/// doc', '///'), 'punctuation.definition.comment.documentation.silk')
  assert.include(scopesAt('/// doc', 'doc'), 'comment.line.documentation.silk')
  assert.include(
    scopesAt('//! module', '//!'),
    'punctuation.definition.comment.documentation.module.silk',
  )
  assert.include(scopesAt('//! module', 'module'), 'comment.line.documentation.module.silk')
  assert.include(scopesAt('/// # Examples', '#'), 'markup.heading.silk')
  assert.include(scopesAt('/// Uses [`Problem`].', 'Problem'), 'markup.underline.link.silk')
  assert.include(scopesAt('/// Uses **care**.', '**care**'), 'markup.bold.silk')
  const fenced = '/// ```silk\n/// effect fn recover(problem: Problem) -> i32\n/// ```'
  assert.include(scopesAt(fenced, 'effect'), 'storage.type.silk')
  assert.include(scopesAt(fenced, 'Problem'), 'entity.name.type.silk')
  assert.include(scopesAt('// plain', '// plain'), 'comment.line.double-slash.silk')
  assert.notInclude(scopesAt('// plain', '// plain'), 'comment.line.documentation.silk')
  const control = 'pub fn main() -> i32 { if true { return 1 } else { return 0 } }'
  assert.include(scopesAt(control, 'if'), 'keyword.control.silk')
  assert.include(scopesAt(control, 'else'), 'keyword.control.silk')
  const match = 'match &mut event { Token { kind, .. } if true => kind _ => 0 }'
  assert.include(scopesAt(match, 'match'), 'keyword.control.silk')
  assert.include(scopesAt(match, '&'), 'keyword.operator.silk')
  assert.include(scopesAt(match, '=>'), 'keyword.operator.silk')
  assert.include(scopesAt(match, '..'), 'punctuation.definition.pattern.rest.silk')
  assert.include(scopesAt(match, 'Token'), 'entity.name.type.silk')
  assert.include(scopesAt(match, '_'), 'variable.language.wildcard.silk')
  const generic = 'fn keep<T>(value: Box<T>) -> Box<T> { return keep<i32>(value) }'
  assert.include(scopesAt(generic, '<'), 'punctuation.definition.type-arguments.begin.silk')
  assert.include(scopesAt(generic, '>'), 'punctuation.definition.type-arguments.end.silk')
  assert.include(scopesAt(generic, 'Box'), 'entity.name.type.silk')
  const nested = 'fn keep<value>(input: Box<Box<i32>>) -> Box<Box<i32>> { return input }'
  assert.include(scopesAt(nested, '<'), 'punctuation.definition.type-arguments.begin.silk')
  assert.include(scopesAt(nested, '>'), 'punctuation.definition.type-arguments.end.silk')
  assert.notInclude(
    scopesAt('pub fn main() -> i32 { if left > (right) { return 1 } return 0 }', '>'),
    'punctuation.definition.type-arguments.end.silk',
  )
  highlighter.dispose()
})
