[package]
name = "silk-compiler"
version = "0.1.0"
root = "src/main.silk"

[build]
composition = { runtimes = [{ name = "synchronous", module = "silk/native_start_sync" }], defaults = ["synchronous"], components = [{ capability = "execution-storage", bindings = [{ operation = "create", module = "silk/execution_storage", declaration = "silk_execution_storage_create" }, { operation = "acquire", module = "silk/execution_storage", declaration = "silk_execution_storage_acquire" }, { operation = "release", module = "silk/execution_storage", declaration = "silk_execution_storage_release" }, { operation = "destroy", module = "silk/execution_storage", declaration = "silk_execution_storage_destroy" }] }], retention = [], requirements = [] }
